#!/bin/sh

TAG=3a9c40c25b2f

full="/setup/hagrid/keys/full/63/80/C07FF6496016E01CF4522841988729C7F3FF"
public="/setup/hagrid/public/keys/pub/63/80/C07FF6496016E01CF4522841988729C7F3FF"

cleanup() {
  pkill -f http-$TAG
  pkill -f hagrid-$TAG
}

(
cd /setup/aptly/public
exec -a http-$TAG python3 -m http.server 3123
) &

(
cd /setup/hagrid
exec -a hagrid-$TAG /root/.cargo/bin/hagrid
) &

trap cleanup SIGTERM SIGINT

wait-for-it -t 0 127.0.0.1:8080
cat /setup/test01.pub | curl -T - http://127.0.0.1:8080
sleep 1
# skip verification
cp "$full" "$public"

wait