#!/usr/bin/env python3
import shutil
from pathlib import Path
from subprocess import run


def main():
    run(["dnf", "install", "-y", "rpm-build"], check=True)
    run(
        [
            "dnf",
            "install",
            "-y",
            "python3-click",
            "python3-frozendict",
            "python3-pyyaml",
            "python3-tomli",
            "python3-tomli-w",
            "python3-devel",
            "python3-setuptools",
            "python3-colorama",
            "python3-jsonschema",
        ],
        check=True,
    )
    dist = Path("/source/dist")
    srpm = str(list(dist.glob("python-pyaptly-*.src.rpm"))[0])
    run(["rpmbuild", "--rebuild", srpm], check=True)
    rpms = Path("/root/rpmbuild/RPMS/noarch")
    file = Path(list(rpms.glob("python3-pyaptly-*.noarch.rpm"))[0])
    shutil.copy2(file, dist)


if __name__ == "__main__":
    main()
