name: Main branch

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug

    - name: Build container
      uses: docker/build-push-action@v5
      with:
        context: compose
        push: true
        tags: ghcr.io/adfinis/pyaptly/cache:latest
        cache-from: type=registry,ref=ghcr.io/adfinis/pyaptly/cache:gha
        cache-to: type=registry,ref=ghcr.io/adfinis/pyaptly/cache:gha,mode=max

  test:
    runs-on: ubuntu-latest
    needs: [cache]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug

    - name: Build container
      uses: docker/build-push-action@v5
      with:
        context: compose
        push: false
        load: true
        tags: ghcr.io/adfinis/pyaptly/cache:latest
        cache-from: type=registry,ref=ghcr.io/adfinis/pyaptly/cache:gha

    - name: Run tests
      run: |
        echo testing
